### ISSUE TITLE
Suggestion: Duration Fix

### ISSUE THREAD

**Issue by Knito58** [Cynosphere/VariablePaxels#1]
There are 3 instruments needed to make one paxel. But the duration still is only of "one". Please add those durations so it makes more sense to have a paxel. Atm I tend to rather have three tools instead of one paxel as it wears off too fast. Nobody would bark if you added some extra duration, say have 4 times the duration of a standard pickaxe of the used material. This would make paxels "the" choice over all other tools as it pays from the moment of making it.

**Comment by Cynosphere** [comment]
Will consider

**Comment by Knito58** [comment]
Thank you.
